### ISSUE TITLE
Sync problem with sickoLooper3

### ISSUE THREAD

**Issue by BMuXBeats** [sickozell/SickoCV#10]
I 've connected sickoLooper3 E.CLK with an external clock (Impromptu Clocked) and set the clock to 120bpm.
Then I've recorded a 2 bars long loop from my electrical guitar. The loop is played in sync to the clock.
If I stop the loop, it'll stop immediately, whe I start it again, it's further in sync again.

BUT: If I stop the clock generator, then restart the clock (run) and press a play button, I won't get the loop in sync played anymore.
I think that normally should be in sync, don't I?

For furhter details I've added two screenshots below:

![grafik](https://github.com/user-attachments/assets/f8f27c85-6219-4a8a-bb3a-589bcc181776)

![grafik](https://github.com/user-attachments/assets/6c31eb76-690b-4df3-a4e8-eafe580a3347)

My System:
LINUX Manjaro 24.08 / KDE Plasma 6.0.5
VCV RACK Free 2.5.2
SickoCV Version 2.6.15

**Comment by sickozell** [comment]
Hello,
sickoLooper can't determine if an external clock is off or it it's just slowing tempo. For this reason the module just keep counting the clocks it receives. But there is the RST button that resets this counter,  
You can map it with uMap receiving the same RUN/STOP trig on the Clocked module.  

![image](https://github.com/user-attachments/assets/6f6874e0-8339-48a9-b56e-58d49e136900)

**Comment by BMuXBeats** [comment]
Hi,
I've tried out your suggestion, but it even doesn't work.
The same behaviour with sickoLooper1, which has an explicit RESET input:

![grafik](https://github.com/user-attachments/assets/e0ace88e-bbc8-47ca-b745-b10313a76817)

By the way: I'm wondering, that the looper wont start/stop really immediately, although both designated buttons are pressed. There's always a little time spare in between.

**Comment by sickozell** [comment]
Could you send me your patch via mail to sickozell@sickozell.org ?

**Comment by BMuXBeats** [comment]
Problem solved!  
  
It was the latency. I forgot, that I have to do a latency measurement after every reboot of my LINUX system.  
I used jack\_iodelay and set my JACK  settings to the adequate values:  
  
 

![](https://github.com/user-attachments/assets/e01fae62-41fe-4980-a317-1dbd0972f404)

Now it works, as it should.  
Sorry for the inconvenience  - it was my fault.

Thank you so much for all your VCV Rack modules, you're published. Great work!
