### ISSUE TITLE
FR: bTogglers: Add Right-click option to switch betwween toggle of gat on and off to one-0shot until armed again

### ISSUE THREAD

**Issue by fractalgee** [sickozell/SickoCV#5]
Rather then have gate stay high there are situations where a gate to turn off after it gets turned on, until armed again and next clock pulse arrives is desired. Right now I have to arm it again to get it to turn off again. So a toggle versus one-shot (momentary gate) option in right-click menu would be awesome.

**Comment by sickozell** [comment]
I don't know if I understood correctly. Are you suggesting to make a TRIG OUTPUT instead of a GATE OUTPUT ?

**Comment by fractalgee** [comment]
Well, a bit longer than a trigger but otherwise yes. That would allow to use it to mute and unmute tracks in MindMeld via the mute trigger in. That way the first trigger/short gate wil mute it, then arm and the next one will unmute it. Sorry if I was unclear.

**Comment by sickozell** [comment]
Ok, a 1ms trigger should be enough, right?

**Comment by fractalgee** [comment]
Yep, just as an option of the right-click menu would be best, so default is as it is now, and alternate mode if wanted/needed would be the best choice to keep things neat and not break patches.

**Comment by sickozell** [comment]
sorry, but maybe I haven't understood yet how you would use it with Mindmeld Mixmaster, can you post a screenshot of your desired patch?

**Comment by fractalgee** [comment]
<img width="1119" alt="bTogglerAndMixMaster" src="https://github.com/sickozell/SickoCV/assets/12473856/d1504eeb-e8c7-41e1-98a6-48013953c128">

Here you go, simplified to the essence

**Comment by sickozell** [comment]
Now it's clear for me. I'll work on it and let you know. Thanks a lot for suggestion.

**Comment by sickozell** [comment]
v2.5.9-beta1 released with a new version of bTogglerCompact. Please, test it and let me know if it's working as expected. Then, this feature could be implemented in others bToggler modules. Thanks

**Comment by fractalgee** [comment]
Works perfectly! Thanks!
