### ISSUE TITLE
Holder Compact menu Gate Out 

### ISSUE THREAD

**Issue by firolightfog** [sickozell/SickoCV#6]
Is this "gate out" option is meant to work like this in Holder Compact? 

![image](https://github.com/sickozell/SickoCV/assets/34127628/c7ffd71e-aec6-4a16-82e9-3f2d666056bd)

**Comment by firolightfog** [comment]
I have no clue what did I do...

![image](https://github.com/sickozell/SickoCV/assets/34127628/37c8c54c-4143-4308-abcf-505fca15c9b3)

**Comment by sickozell** [comment]
Yes, GATE OUT is a T&H option only

**Comment by sickozell** [comment]
Yes, GATE OUT is a T&H option only
