### ISSUE TITLE
Feature suggestion - Inputs for some parameters for SickoSampler 2

### ISSUE THREAD

**Issue by jaffasplaffa** [sickozell/SickoCV#7]
Hey :) 

Just discovered your modules today. They are pretty awesome. I am looking for something to replace Lomas sampler, and SickoSampler 2 seems like a very good candidate. It's polyphonic(very important) and offers stereo files, which Lomas has not got either. Lomas take a bunch of modules to make something polyphonic out of it. Lomas has inputs start and end points and I managed to add my own loop on/off input which is not available in the original version. It works okay, but it's a hell of a mess. And I also like that you have time stretch build into your sampler :) 

I was wondering if you would take a couple of suggestions for a new version?

I would like to suggest:
1. Add inputs for the start/end points for Cue.
2. Add inputs for the start/end points for Loop. 
3. Add an input for the Loop on/off.
4. Add input for the Reverse playback function for Cue.

I would even be happy if the knobs where replaced with inputs, as I see the UI could be a bit crowded with all this added. That would probably be a version 2.1, to keep the original one compatible with existing setups. This would make a it a hell of a drumloop slicer, where you can change settings, on the go, with other modules.

I hope you will take my suggestion into consideration!

Thanks in advance,
Jakob

**Comment by jaffasplaffa** [comment]
Thank you for the feedback :) 

The start and end point(The other params too), I would like to be able to set pr voice. Most modules with knobs seems to set the knob values for all voices at once, all voices changes their pitch right away, if you edit the pitch knob. So not sure this will work. But I will give Umap a go and see how it behaves :)

**Comment by sickozell** [comment]
Maybe now I understand.  
I don't think sickoSampler would work adequately because it is designed to operate in polyphony based on the v/Oct input, not the triggers.  
For the use you are  requesting, maybe a module specifically designed for splicing would be needed
