### ISSUE TITLE
SickoSampler2 still crashes a lot for me

### ISSUE THREAD

**Issue by Cubistguitar** [sickozell/SickoCV#8]
[log.txt](https://github.com/sickozell/SickoCV/files/15003894/log.txt)
Crashed about 8 times today over a hour and half

I have brought this up in forum and sent resources to help identify the crashes.

I assume it not easy to spot the issue, I am win 10 Rack2 pro 2.4.1.

If you need a crashing patch I can oblige.

Seems to happen when I spin the stretch knobs to lowest value while sample is playing.

[log.txt](https://github.com/sickozell/SickoCV/files/15003897/log.txt)

**Comment by sickozell** [comment]
I'm sorry, but I need a logfile where the crashes are logged, even to be sure that it's  sickoSampler the faulting module. I don't find any crash in your attachments.

**Comment by sickozell** [comment]
After a deep debug this issue is fixed with v2.6.10 update
